TE_dir: /p/projects/zeean/calibration/tradingeconomics_data/
regions:
  - USA
  - CHN
  - JPN
  - DEU
  - GBR
  - FRA
  - IND
  - ITA
  - BRA
  - CAN
  - KOR
  - RUS
  - ESP
  - AUS
  - MEX
  - IDN
  - TUR
  - SAU
  - ARG
  - ZAF
  - SGP
  - THA
  - NLD
sectors:
  - Manufacturing Production
  - Industrial Production
  - Capacity Utilization
  - TREQ
  - Steel Production
  - Electricity Production
years_to_observe:
  - 2001:
      1: 1
      2: 1
      3: 1
      4: 1
      5: 1
      6: 1
      7: 1
      8: 1
      9: 1
      10: 1
      11: 1
      12: 1
  - 2002:
      1: 1
      2: 1
      3: 1
      4: 1
      5: 1
      6: 1
      7: 1
      8: 1
      9: 1
      10: 1
      11: 1
      12: 1
  - 2003:
      1: 1
      2: 1
      3: 1
      4: 1
      5: 1
      6: 1
      7: 1
      8: 1
      9: 1
      10: 1
      11: 1
      12: 1
  - 2004:
      1: 1
      2: 1
      3: 1
      4: 1
      5: 1
      6: 1
      7: 1
      8: 1
      9: 1
      10: 1
      11: 1
      12: 1
  - 2005:
      1: 1
      2: 1
      3: 1
      4: 1
      5: 1
      6: 1
      7: 1
      8: 1
      9: 1
      10: 1
      11: 1
      12: 1
  - 2006:
      1: 1
      2: 1
      3: 1
      4: 1
      5: 1
      6: 1
      7: 1
      8: 1
      9: 1
      10: 1
      11: 1
      12: 1
  - 2007:
      1: 1
      2: 1
      3: 1
      4: 1
      5: 1
      6: 1
      7: 1
      8: 1
      9: 1
      10: 1
      11: 1
      12: 1
  - 2008:
      1: 1
      2: 1
      3: 1
      4: 1
      5: 1
      6: 1
      7: 1
      8: 1
      9: 1
      10: 1
      11: 1
      12: 1
  - 2009:
      1: 1
      2: 1
      3: 1
      4: 1
      5: 1
      6: 1
      7: 1
      8: 1
      9: 1
      10: 1
      11: 1
      12: 1
  - 2010:
      1: 1
      2: 1
      3: 1
      4: 1
      5: 1
      6: 1
      7: 1
      8: 1
      9: 1
      10: 1
      11: 1
      12: 1
year_validation: 2011
num_params_per_region: 10
params_min: 0
params_max: 1
