TE_dir: /p/projects/zeean/calibration/tradingeconomics_data/
regions:
  - USA
  - CHN
  - JPN
  - DEU
  - GBR
  - FRA
  - IND
  - ITA
  - BRA
  - CAN
  - KOR
  - RUS
  - ESP
  - AUS
  - MEX
  - IDN
  - TUR
  - SAU
  - ARG
  - ZAF
  - SGP
  - THA
  - NLD
sectors:
  - Manufacturing Production
  - Industrial Production
  - Capacity Utilization
  - TREQ
  - Steel Production
  - Electricity Production
years_to_observe:
  - 2001
  - 2002
  - 2003
  - 2004
  - 2005
  - 2006
  - 2007
  - 2008
  - 2009
  - 2010
year_validation: 2011
num_params_per_region: 10
params_min: 0
params_max: 1
